# Generated by Django 3.0.6 on 2020-06-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('url', models.TextField()),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(upload_to='product_images')),
                ('icon', models.ImageField(upload_to='product_images')),
                ('votes_total', models.IntegerField(default=1)),
                ('body', models.TextField()),
            ],
        ),
    ]
