# Generated by Django 3.0.6 on 2020-08-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200608_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='icon',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='product_images/'),
        ),
    ]
